### ISSUE TITLE
运行爆错

### ISSUE THREAD

**Issue by yazhouZhang** [xiaogliu/react_native_complete_demo#2]
![simulator screen shot - iphone x - 2018-04-21 at 15 38 38](https://user-images.githubusercontent.com/13583230/39081782-57f627f0-44fc-11e8-9077-a3338cc62bee.png)

**Comment by xiaogliu** [comment]
重新拉取仓库，使用 yarn 安装依赖，通过 xcode 运行试下？

**Comment by xiaogliu** [comment]
@yazhouZhang 重新拉取仓库，使用 yarn 安装依赖，通过 xcode 运行试下？

**Comment by yazhouZhang** [comment]
react_native_complete_demo-master/src/screens/ScreenHome目录下，index.js注释掉
componentDidMount() {
    // 隐藏启动页
   // SplashScreen.hide();
  }
 // SplashScreen.hide(); 就没报错

**Comment by xiaogliu** [comment]
但这样启动页就没法消失了。我刚才拉下代码自己跑了下ok（环境见 readme），参考下这个 issue [undefined is not an object (evaluating '_reactNativeSplashScreen2.default.hide') #100](https://github.com/crazycodeboy/react-native-splash-screen/issues/100)
